// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/test.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Exchange int32

const (
	Exchange_EX_UNKNOWN Exchange = 0
	Exchange_TYPE_SH    Exchange = 1
	Exchange_TYPE_SZ    Exchange = 2
)

var Exchange_name = map[int32]string{
	0: "EX_UNKNOWN",
	1: "TYPE_SH",
	2: "TYPE_SZ",
}

var Exchange_value = map[string]int32{
	"EX_UNKNOWN": 0,
	"TYPE_SH":    1,
	"TYPE_SZ":    2,
}

func (x Exchange) String() string {
	return proto.EnumName(Exchange_name, int32(x))
}

func (Exchange) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_332ab25c6b5a960c, []int{0}
}

type Test struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type                 Exchange `protobuf:"varint,2,opt,name=type,proto3,enum=example.Exchange" json:"type,omitempty"`
	Reps                 []int64  `protobuf:"varint,3,rep,packed,name=reps,proto3" json:"reps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_332ab25c6b5a960c, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Test) GetType() Exchange {
	if m != nil {
		return m.Type
	}
	return Exchange_EX_UNKNOWN
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func init() {
	proto.RegisterEnum("example.Exchange", Exchange_name, Exchange_value)
	proto.RegisterType((*Test)(nil), "example.Test")
}

func init() { proto.RegisterFile("protos/test.proto", fileDescriptor_332ab25c6b5a960c) }

var fileDescriptor_332ab25c6b5a960c = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0xb3, 0x85, 0xd8, 0x53, 0x2b, 0x12, 0x73,
	0x0b, 0x72, 0x52, 0x95, 0xc2, 0xb9, 0x58, 0x42, 0x52, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x73,
	0x12, 0x93, 0x52, 0x73, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x55, 0x2e,
	0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x41, 0x3d, 0xa8, 0x2e,
	0x3d, 0xd7, 0x8a, 0xe4, 0x8c, 0xc4, 0xbc, 0xf4, 0xd4, 0x20, 0xb0, 0xb4, 0x90, 0x10, 0x17, 0x4b,
	0x51, 0x6a, 0x41, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0x73, 0x10, 0x98, 0xad, 0x65, 0xc2, 0xc5,
	0x01, 0x53, 0x25, 0xc4, 0xc7, 0xc5, 0xe5, 0x1a, 0x11, 0x1f, 0xea, 0xe7, 0xed, 0xe7, 0x1f, 0xee,
	0x27, 0xc0, 0x20, 0xc4, 0xcd, 0xc5, 0x1e, 0x12, 0x19, 0xe0, 0x1a, 0x1f, 0xec, 0x21, 0xc0, 0x88,
	0xe0, 0x44, 0x09, 0x30, 0x25, 0xb1, 0x81, 0x9d, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x67,
	0x02, 0x4a, 0x42, 0xb3, 0x00, 0x00, 0x00,
}
