
###### sunquan 2020-09-24 add
export LANG="en_US.UTF-8"
alias python=python3
alias sed=gsed
# 覆盖zsh builtin 的 time 关键字
alias time='/usr/bin/time -h'
alias ss='lsof -nP -i4TCP | grep LISTEN'
alias ll='ls -al -h'
alias st='git status'
alias gsh='git show --pretty=fuller'
alias rm_go_unit_test='find * -type f -name "*_test.go"|xargs rm'
alias cloc_by_user='git ls-files | while read f; do git blame --line-porcelain $f | grep "^author "; done | sort -f | uniq -ic | sort -rn'
alias go_build_linux='GOOS=linux GOARCH=amd64 go build -v .'
